version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: logbook-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: logbook
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dummy
    volumes:
      - pgdata:/var/lib/postgresql/data

  #TODO likely remove for manual data manipulation and i'd rather access via SQL console
  pgadmin:
    image: dpage/pgadmin4
    container_name: logbook-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@logbook.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
