### Base URL
@host = localhost:8080
# FOR AWS
#@host = logbook-alb-1951812183.us-east-2.elb.amazonaws.com

### Get Goals
GET http://{{host}}/user/goals
Content-Type: application/json

### Get Today Summary
GET http://{{host}}/user/today/summary
Content-Type: application/json

### Get Activities of Type
@exerciseTypeGet = pushups
GET http://{{host}}/log/{{exerciseTypeGet}}
Content-Type: application/json


### Get Time Series Data for Activities of Type
GET http://{{host}}/log/{{exerciseTypeGet}}/timeSeriesData
Content-Type: application/json

### Log N of exerciseType
@exerciseType = pushups
@quantity = 10
POST http://{{host}}/log/{{exerciseType}}?quantity={{quantity}}
Content-Type: application/json

### Check Health Status
GET http://{{host}}/actuator/health
Content-Type: application/json
