### Base URL
#@host = http://localhost:8080
# FOR AWS
@host = https://api.alponcher.us

### Register
POST {{host}}/user/register
Content-Type: application/json

{
  "username": "alice",
  "email": "alice@example.com",
  "password": "secure123"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Login
POST {{host}}/user/login
Content-Type: application/json

{
  "id": "aponcher@mac.com",
  "password": "abc"
}
> {%
    client.global.set("auth_token", response.body.token);
%}

### Get Goals
GET {{host}}/user/goals
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get Today Summary
GET {{host}}/user/today/summary
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get Activities of Type
@exerciseTypeGet = pushups
GET {{host}}/log/{{exerciseTypeGet}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### Get Time Series Data for Activities of Type
GET {{host}}/log/{{exerciseTypeGet}}/timeSeriesData
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Log N of exerciseType
@exerciseType = pushups
@quantity = 10
POST {{host}}/log/{{exerciseType}}?quantity={{quantity}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Check Health Status
GET {{host}}/actuator/health
Content-Type: application/json

### Check Health Status
GET http://api.alponcher.us/actuator/health
Content-Type: application/json
#Authorization: Bearer {{auth_token}}
