name: Terraform Infra

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
    paths:
      - 'terraform/*.tf'  # Trigger only when .tf files are modified


jobs:
  terraform:
    name: 'Terraform Plan/Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # or your desired version

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Mvn install (to resolve version)
        run: mvn install -DskipTests

      - name: Extract version from POM
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -Ev '(^\[|Download\w+:)')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Show version
        run: echo "Using app_version=$VERSION"

      - name: Write app version to tfvars file
        run: echo "app_version = \"${{ env.VERSION }}\"" > terraform/app_version.auto.tfvars

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check

      - name: Print tfvars
        run: |
          cd terraform
          cat terraform.tfvars
          cat app_version.auto.tfvars

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -input=false -no-color > plan.txt
          cat plan.txt
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        run: |
          PLAN_OUTPUT=$(cat terraform/plan.txt)
          PLAN_COMMENT="### Terraform Plan Result\n\`\`\`\n${PLAN_OUTPUT}\n\`\`\`"
          PLAN_COMMENT="${PLAN_COMMENT//'%'/'%25'}"
          PLAN_COMMENT="${PLAN_COMMENT//$'\n'/'%0A'}"
          PLAN_COMMENT="${PLAN_COMMENT//$'\r'/'%0D'}"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d "{\"body\": \"$PLAN_COMMENT\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

